name: cicd

on:
  push:
    branches:["main"]


  wokflow_dispatch:

persmissions:
  contents: read
    pages: write
    id-token: write

concurrency:
  group:"pages"
  cancel-in-progress: true

jobs:
  # CI
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        users: actions/configure-pages@v2
      - name: Buils with Jelyll
        uses: actions/jekeyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
# CD
deploy:
  enviroment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Deploy to Github pages
      id: deployment
      uses: action/deploy-pages@v1



